module.exports = {
  ROLES: {
    COMPRADOR: 'COMPRADOR',
    VENDEDOR: 'VENDEDOR',
    ADMINISTRADOR: 'ADMINISTRADOR',
  },

  APPROVAL_STATUS: {
    PENDIENTE: 'PENDIENTE',
    APROBADO: 'APROBADO',
    RECHAZADO: 'RECHAZADO',
  },

  PRODUCT_STATE: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    TEMP_DISABLED: 'TEMP_DISABLED',
  },

  SHOPPING_LIST_STATUS: {
    OPEN: 'OPEN',
    COMPLETED: 'COMPLETED',
  },

  TICKET_STATUS: {
    PENDIENTE: 'PENDIENTE',
    RESPONDIDO: 'RESPONDIDO',
    EN_ESPERA_DE_RESPUESTA: 'EN_ESPERA_DE_RESPUESTA',
    ATENDIDO: 'ATENDIDO',
  },

  TICKET_TARGET: {
    ADMIN: 'ADMIN',
    STORE: 'STORE',
  },

  TICKET_CLOSE_REASON: {
    ACCEPTED: 'ACCEPTED',
    NO_BUYER_RESPONSE_7D: 'NO_BUYER_RESPONSE_7D',
    ADMIN_CLOSED: 'ADMIN_CLOSED',
  },

  SUBSCRIPTION_STATUS: {
    ACTIVE: 'ACTIVE',
    EXPIRED: 'EXPIRED',
  },

  SUBSCRIPTION_REQUEST_STATUS: {
    PENDIENTE: 'PENDIENTE',
    APROBADO: 'APROBADO',
    RECHAZADO: 'RECHAZADO',
    ELIMINADO: 'ELIMINADO',
  },

  PLAN_TYPE: {
    ESTANDAR: 'ESTANDAR',
    PREMIUM: 'PREMIUM',
  },

  AUTH_ERROR_CODES: {
    ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  },

  AUTH_MESSAGES: {
    ACCOUNT_DISABLED: 'Tu cuenta ha sido inhabilitada por un administrador',
  },

  RATING_WINDOW_DAYS: 14,
  TICKET_SELLER_CLOSE_DAYS: 7,
  TIMEZONE: 'America/Lima',

  UPLOAD: {
    MAX_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
    MAX_PHOTOS_PER_ENTITY: 5,
    ALLOWED_IMAGE_TYPES: ['image/jpeg', 'image/png', 'image/webp'],
    ALLOWED_RECEIPT_TYPES: ['image/jpeg', 'image/png', 'image/webp', 'application/pdf'],
  },
};
